apiVersion: v1
kind: Service
metadata:
  name: fat-test-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 3007
      protocol: TCP
      targetPort: 3007
  selector:
    app: fat-test
