server:
  port: 9052
spring:
  datasource:
    url: jdbc:mysql://cloudsql-proxy-service/fat_test?autoReconnect=true&useSSL=false
    username: lf2lf211
    password: lf2lf211
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: self-racing
project:
  hostName: d87b.com