server:
  port: 9052
spring:
  datasource:
    url: jdbc:mysql://35.194.106.1:3306/yuanbao_system?autoReconnect=true&useSSL=false
    username: d87b_cowcow
    password: 1qaz@WSX3edc
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: self-racing
project:
  hostName: d87b.com