server:
  port: 9052
spring:
  datasource:
    url: jdbc:mysql://10.4.240.3:3306/fat_test?autoReconnect=true&useSSL=false
    username: lf2lf211
    password: lf2lf211
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: self-racing
project:
  hostName: d87b.com